# SELECT COUNT(*) FROM ANIMAL_INS 

# 특정 조건 걸어서 COUNT
# SELECT COUNT(*) FROM ANIMAL_INS WHERE ANIMAL_TYPE = 'Dog'

# WHERE문 쓰지 않고 조건 걸기
# SELECT COUNT(CASE WHEN ANIMAL_TYPE = 'Dog') FROM ANIMAL_INS

# 중복제거 
# SELECT COUNT(DISTINCT ANIMAL_TYPE) FROM ANIMAL_INS

